version: '3'

services:
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:3.4
    
  core:
    container_name: openhim-core
    build: ../../../openhim-core-js/
    image: openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
      # - api_authWindowSeconds=60
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
    volumes:
      - ../../../openhim-core-js/src/:/src/openhim-core/src/
  
  console:
    container_name: openhim-console
    build: ../../../openhim-console
    image: openhim-console
    ports:
        - "9000:9000"
    volumes:
      - ../../../openhim-console/app/scripts/:/src/openhim-console/app/scripts/
      - ../../../openhim-console/app/views/:/src/openhim-console/app/views/
      - ../../../openhim-console/app/styles/:/src/openhim-console/app/styles/
      - ../../../openhim-console/app/index.html:/src/openhim-console/app/index.html
    